<?php

test('home page can be rendered with portfolio and navbar content', function () {
    $response = $this->get(route('home'));

    $response
        ->assertOk()
        ->assertSee('Me')
        ->assertSee('Blogs')
        ->assertSee('mc-logo.png')
        ->assertSee('Mark Cole')
        ->assertSee('Full Stack Laravel Developer')
        ->assertSee('cole-1side.jpeg')
        ->assertSee('Kampala, Central Region, Uganda')
        ->assertSee('markcole683@gmail.com')
        ->assertSee('LinkedIn')
        ->assertSee('mark-cole-mukisa')
        ->assertSee('@MarkColeMukisa')
        ->assertSee('WhatsApp')
        ->assertSee('About')
        ->assertSee('modern full-stack Laravel web developer')
        ->assertSee('What I Build With')
        ->assertSee('My Development Approach')
        ->assertSee('Stack')
        ->assertSee('aria-label="Laravel"', false)
        ->assertSee('aria-label="Livewire"', false)
        ->assertSee('aria-label="Postgres"', false)
        ->assertSee('aria-label="Resend"', false)
        ->assertSee('aria-label="Laravel Cloud"', false)
        ->assertSee('aria-label="Tailwind"', false)
        ->assertSee('aria-label="Git"', false)
        ->assertSee('aria-label="GitHub"', false)
        ->assertSee('My Projects & Platforms')
        ->assertSee('Kian Rover')
        ->assertSee('Portfolio Mgt')
        ->assertSee('Event App')
        ->assertSee('Built by')
        ->assertSee('MarkCole (FullStack Laravel Developer)')
        ->assertSee('aria-label="Toggle Theme"', false)
        ->assertSee('Ctrl K')
        ->assertSee('grid-cols-[auto_minmax(0,1fr)]', false)
        ->assertSee('grid-cols-[7.5rem_minmax(0,1fr)]', false)
        ->assertSee('wrap-anywhere', false)
        ->assertSee('min-[390px]:inline', false);
});
